---
namespace: 'sbaerlocher'
name: 'virtualization'
version: 0.0.6
readme: README.md
authors:
  - 'Simon Baerlocher (https://sbaerlocher.ch)'
description: 'Ansible Collection for virtualization.'
license: MIT
tags:
  - virtualization
dependencies: {}
repository: 'https://www.github.com/sbaerlocher/ansible.virtualization'
documentation: 'https://sbaerlocher.github.io/ansible.virtualization'
homepage: 'https://sbaerlocher.ch/projects/ansible.virtualization'
issues: 'https://www.github.com/sbaerlocher/ansible.virtualization/issues'
