---
# vars file for virtualbox

# Here you can specify the version to be installed.
# By default, the role itself searches for the latest version.
virtualbox_version: '{{ current_version }}'

# Repository url from where virtualbox can be installed.
virtualbox_repository: 'https://download.virtualbox.org/virtualbox'

# Version of Virtualbox that is to be installed.
# By default, it chooses the latest version.
virtualbox_packages: "VirtualBox-{{ virtualbox_version.split('.')[0] + '.' + virtualbox_version.split('.')[1] }}"
