---
- name: Prepare
  hosts: all
  tasks:
    - name: Install apt-transport-https on Debian family
      apt:
        name:
          - apt-transport-https
          - gnupg
        update_cache: true
      when:
        - ansible_os_family == 'Debian'
