---
# tasks file for virtualbox_extension_pack

- name: 'Linux : Download VirtualBox extension pack'
  get_url:
    url: '{{ virtualbox_extension_pack_url }}'
    dest: '{{ virtualbox_extension_pack_dest }}'

- name: 'Linux : Install VirtualBox extension pack'
  become: true
  shell: 'VBoxManage extpack install --replace --accept-license={{ virtualbox_extension_pack_license_hash }} {{ virtualbox_extension_pack_dest }}'
