---
# defaults file for virtio

# here you can specify the version to be installed.
# By default, the role itself searches for the latest version.
virtio_version: '{{ current_version | default(0) }}'

# Variable to check if it is a virtual machine on an Ovirt Cluster.
virtio_win_ovirt: false

# Determines which Windows version the Hosts
# system has to install the correct driver version.
virtio_driver_directory: >-
  {% if 'Windows Server 2019' in ansible_distribution -%}
    {% set virt_dir = '2k19' %}
  {% elif 'Windows Server 2016' in ansible_distribution -%}
    {% set virt_dir = '2k16' %}
  {% elif 'Windows Server 2012 R2' in ansible_distribution -%}
    {% set virt_dir = '2k12R2' %}
  {% elif 'Windows Server 2008 R2' in ansible_distribution -%}
    {% set virt_dir = '2k8R2' %}
  {% elif 'Windows 10' in ansible_distribution -%}
    {% set virt_dir = 'w10' %}
  {% else -%}
    {% set virt_dir = 'w10' %}
  {%- endif %}{{ virt_dir }}

# Allows to execute the alway part in the block.
virtio_block_always: true
